chore: Make the `range_proof_commitment` field of the `SecretKeyShareEncryptionAndProof` struct public
dwallet-labs/2pc-mpc pull request #20
Opened 2024-07-10 13:34 UTC by ItayLevyOfficial

2024-07-10 14:49 UTC, zeevmoney approved these changes
@ycscaly

2024-08-04 22:08 UTC, ycscaly requested changes

2024-08-04 22:08 UTC, ycscaly commented on src/dkg/centralized_party/decommitment_round.rs
> +            decentralized_party_public_key_share.clone(),
what is this? how can a code like this be included in a pr?

2024-08-04 22:08 UTC, ycscaly commented on src/dkg/decentralized_party.rs
> +    pub range_proof_commitment: RangeProofCommitmentValue,
no no no, this range proof commitment is one-time use, for a single proof.
This is definitely not where you should take it from - doing so will break the proof

2024-08-04 22:08 UTC, ycscaly commented on src/dkg/centralized_party/decommitment_round.rs
> +    pub public_key_share: GroupElementValue,
This is not where you should take it from. You should take it from the [DKG output](https://github.com/dwallet-labs/2pc-mpc/blob/c509064e18f5261ec298d1d4d697dfb260ed85fe/src/dkg/decentralized_party/decommitment_proof_verification_round.rs#L29).

2024-08-05 10:38 UTC, closed without merging