chore: Add a static signature verification function to `signature_threshold_decryption_round` party
dwallet-labs/2pc-mpc pull request #24
Opened 2024-08-01 13:58 UTC by ItayLevyOfficial

2024-08-01 16:23 UTC, ycscaly requested changes

2024-08-01 16:23 UTC, ycscaly commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +            .map_err(|_| Error::SignatureVerification)?;
```suggestion
            .map_err(|_| Error::MaliciousDesignatedDecryptingParty)?;
```
Please change it so, and simply remove the `PartyID` from `MaliciousDesignatedDecryptingParty` as I asked before

2024-08-01 16:23 UTC, ycscaly commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +    pub fn verify_decrypted_signature_static(
```suggestion
    pub fn verify_decrypted_signature_internal(
```

2024-08-01 16:23 UTC, ycscaly commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +        nonce_x_coordinate: GroupElement::Scalar,
```suggestion
        nonce_x_coordinate: GroupElement::Scalar,
        signature_s: GroupElement::Scalar,
```
This is the correct order as signature is `(r, s)` tuples

2024-08-01 16:23 UTC, ycscaly commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +        message: GroupElement::Scalar,
```suggestion
        message: GroupElement::Scalar,
```
probably should be first

2024-08-02 09:52 UTC, ItayLevyOfficial commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +        message: GroupElement::Scalar,
Why? It was third in `verify_signature`

2024-08-02 10:10 UTC, ItayLevyOfficial commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +        message: GroupElement::Scalar,
Why? It's third in `verify_signature`

2024-08-02 10:11 UTC, ItayLevyOfficial commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +            .map_err(|_| Error::SignatureVerification)?;
I didn't do it because it's being used [here](https://github.com/dwallet-labs/2pc-mpc/blob/8435c760e7fff5104a58812557544f5fdcf28ac0/src/sign/decentralized_party/identifiable_abort/signature_partial_decryption_verification_round.rs#L116) - do you want me to remove it from there as well?

2024-08-03 20:45 UTC, ycscaly commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +            .map_err(|_| Error::SignatureVerification)?;
yeah

2024-08-04 08:34 UTC, ycscaly requested changes
see comment

2024-08-04 10:48 UTC, zeevmoney requested changes
see comments

2024-08-04 10:48 UTC, zeevmoney commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +    pub fn verify_decrypted_signature_internal(
@ycscaly 
Why `Internal` and `pub` function? 
`static` was also a bad name, so maybe consider `wrapper`

2024-08-04 12:55 UTC, ycscaly commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +    pub fn verify_decrypted_signature_internal(
I'm good with whatever you choose here

2024-08-04 15:31 UTC, zeevmoney approved these changes

2024-08-04 22:05 UTC, ycscaly approved these changes

2024-08-04 22:05 UTC, ycscaly commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
> +    pub fn verify_decrypted_signature_wrapper(
```suggestion
    pub fn verify_decrypted_signature(
```
If anything, this is the internal function so the other one should be called `wrapper`

2024-08-04 22:05 UTC, ycscaly commented on src/sign/decentralized_party/signature_threshold_decryption_round.rs
>      pub fn verify_decrypted_signature(
```suggestion
    pub fn verify_decrypted_signature_in_session(
```
Perhaps this is a suitable name

2024-08-05 09:21 UTC, merged